# application.yml

# Server Configuration
server:
  port: 8080  # Port number where the service will run

# Spring Datasource Configuration (Database connection details)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doctordatabase  # MySQL database URL
    username: root  # Database username
    password: root  # Database password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver class

  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the database schema
    show-sql: true  # Show SQL queries in the logs

# Hibernate dialect for MySQL
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
